<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) 2002, Zikula Development Team
 * @link http://www.zikula.org
 * @version $Id: Admin.php 439 2010-07-06 14:49:42Z drak $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Zikula_Value_Addons
 * @subpackage Quotes
 */

class Quotes_Controller_Admin extends Zikula_Controller
{
    /**
     * Quotes main administration function
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function main()
    {
        // security check
        if (!SecurityUtil::checkPermission('Quotes::', '::', ACCESS_EDIT)) {
            return LogUtil::registerPermissionError();
        }

        $this->view->setCaching(false);        

        // return the output that has been generated by this function
        return $this->view->fetch('quotes_admin_main.htm');
    }

    /**
     * Display form to create a new quote
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function newquote()
    {
        // security check
        if (!SecurityUtil::checkPermission('Quotes::', '::', ACCESS_ADD)) {
            return LogUtil::registerPermissionError();
        }

        // get all module vars
        $modvars = ModUtil::getVar('Quotes');

        $this->view->setCaching(false);

        if ($modvars['enablecategorization']) {
            $catregistry = CategoryRegistryUtil::getRegisteredModuleCategories('Quotes', 'quotes');

            $this->view->assign('catregistry', $catregistry);
        }

        // assign the module vars
        $this->view->assign($modvars);

        return $this->view->fetch('quotes_admin_new.htm');
    }

    /**
     * Display full list of quotes
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function view($args)
    {
        // security check
        if (!(SecurityUtil::checkPermission('Quotes::', '::', ACCESS_READ))) {
            return LogUtil::registerPermissionError();
        }

        // Get parameters from whatever input we need.
        $startnum = FormUtil::getPassedValue('startnum', isset($args['startnum']) ? $args['startnum'] : null, 'GET');
        $keyword  = FormUtil::getPassedValue('quotes_keyword', isset($args['quotes_keyword']) ? $args['quotes_keyword'] : '', 'POST');
        $author   = FormUtil::getPassedValue('quotes_author', isset($args['quotes_author']) ? $args['quotes_author'] : '', 'POST');
        $property = FormUtil::getPassedValue('quotes_property', isset($args['quotes_property']) ? $args['quotes_property'] : null, 'POST');
        $category = FormUtil::getPassedValue("quotes_{$property}_category", isset($args["quotes_{$property}_category"]) ? $args["quotes_{$property}_category"] : null, 'POST');
        $clear    = FormUtil::getPassedValue('clear', false, 'POST');
        if ($clear) {
            $property = $category = $keyword = $author = null;
        }

        // get all module vars
        $modvars = ModUtil::getVar('Quotes');

        if ($modvars['enablecategorization']) {
            $catregistry  = CategoryRegistryUtil::getRegisteredModuleCategories('Quotes', 'quotes');
            $properties = array_keys($catregistry);

            // validate and build the category filter - mateo
            if (!empty($property) && in_array($property, $properties) && !empty($category)) {
                $catFilter = array($property => $category);
            }

            // assign a default property - mateo
            if (empty($property) || !in_array($property, $properties)) {
                $property = $properties[0];
            }

            // plan ahead for ML features
            $propArray = array();
            foreach ($properties as $prop) {
                $propArray[$prop] = $prop;
            }
        }

        // get the matching quotes
        $quotes = ModUtil::apiFunc('Quotes', 'user', 'getall',
                array('startnum' => $startnum,
                'numitems' => $modvars['itemsperpage'],
                'keyword'  => $keyword,
                'author'   => $author,
                'category' => isset($catFilter) ? $catFilter : null,
                'catregistry'  => isset($catregistry) ? $catregistry : null));

        $items = array();
        foreach ($quotes as $key => $quote)
        {
            // options for the item
            $options = array();
            if (SecurityUtil::checkPermission('Quotes::', "$quote[author]::$quote[qid]", ACCESS_EDIT)) {
                $quotes[$key]['options'][] = array('url'   => ModUtil::url('Quotes', 'admin', 'modify', array('qid' => $quote['qid'])),
                        'image' => 'xedit.gif',
                        'title' => $this->__('Edit'));

                if (SecurityUtil::checkPermission('Quotes::', "$quote[author]::$quote[qid]", ACCESS_DELETE)) {
                    $quotes[$key]['options'][] = array('url'   => ModUtil::url('Quotes', 'admin', 'delete', array('qid' => $quote['qid'])),
                            'image' => '14_layer_deletelayer.gif',
                            'title' => $this->__('Delete'));
                }
            }
            $items[] = $quotes[$key];
        }

        $this->view->setCaching(false);

        // assign the default language
        $this->view->assign('lang', ZLanguage::getLanguageCode());

        // assign the items and modvars to the template
        $this->view->assign('quotes', $items);
        $this->view->assign($modvars);

        // add the current filters
        $this->view->assign('quotes_author', $author);
        $this->view->assign('quotes_keyword', $keyword);

        // assign the categories information if enabled
        if ($modvars['enablecategorization']) {
            $this->view->assign('catregistry', $catregistry);
            $this->view->assign('numproperties', count($propArray));
            $this->view->assign('properties', $propArray);
            $this->view->assign('property', $property);
            $this->view->assign("category", $category);
        }

        // assign the values for the smarty plugin to produce a pager
        $this->view->assign('pager', array('itemsperpage' => $modvars['itemsperpage'],
                'numitems' => ModUtil::apiFunc('Quotes', 'user', 'countitems',
                array('keyword'  => $keyword,
                'author'   => $author,
                'category' => isset($catFilter) ? $catFilter : null))));

        return $this->view->fetch('quotes_admin_view.htm');
    }

    /**
     * Edit quote
     * @author The Zikula Development Team
     * @param 'qid' Quote id to delete
     * @param 'qauther' Author of quote to delete
     * @param 'confirm' Delete confirmation
     * @return mixed HTML string if confirm is null, true otherwise
     */
    public function modify($args)
    {
        // get parameters from whatever input we need.
        $qid = FormUtil::getPassedValue('qid', isset($args['qid']) ? $args['qid'] : null, 'GET');
        $objectid = FormUtil::getPassedValue('objectid', isset($args['objectid']) ? $args['objectid'] : null, 'GET');

        // check to see if we have been passed $objectid, the generic item identifier.
        if (!empty($objectid)) {
            $qid = $objectid;
        }

        // get the quote
        $quote = ModUtil::apiFunc('Quotes', 'user', 'get', array('qid' => $qid));
        if (!$quote) {
            return DataUtil::formatForDisplayHTML($this->__('No such Quote found.'));
        }

        // security check
        if (!SecurityUtil::checkPermission('Quotes::', "$quote[author]::$qid", ACCESS_EDIT)) {
            return LogUtil::registerPermissionError();
        }

        // get all module vars
        $modvars = ModUtil::getVar('Quotes');

        // create output object
        $this->view = & Zikula_View::getInstance('Quotes', false);

        if ($modvars['enablecategorization']) {
            // load the category registry util
            $catregistry = CategoryRegistryUtil::getRegisteredModuleCategories('Quotes', 'quotes');

            $this->view->assign('catregistry', $catregistry);
        }

        // assign the item and module vars
        $this->view->assign($quote);
        $this->view->assign($modvars);

        // return the output that has been generated by this function
        return $this->view->fetch('quotes_admin_modify.htm');
    }

    /**
     * Delete selected quote
     * @author The Zikula Development Team
     * @param 'qid' Quote id to delete
     * @param 'qauther' Author of quote to delete
     * @param 'confirm' Delete confirmation
     * @return mixed HTML string if confirm is null, true otherwise
     */
    public function delete($args)
    {
        // get parameters from whatever input we need.
        $qid = FormUtil::getPassedValue('qid', isset($args['qid']) ? $args['qid'] : null, 'GETPOST');
        $objectid = FormUtil::getPassedValue('objectid', isset($args['objectid']) ? $args['objectid'] : null, 'POST');
        $confirmation = FormUtil::getPassedValue('confirmation', null, 'POST');
        if (!empty($objectid)) {
            $qid = $objectid;
        }

        // get the quote
        $item = ModUtil::apiFunc('Quotes', 'user', 'get', array('qid' => $qid));
        if ($item == false) {
            return LogUtil::registerError ($this->__('No such Quote found.'));
        }

        // security check
        if (!SecurityUtil::checkPermission('Quotes::', "$item[author]::$qid", ACCESS_DELETE)) {
            return LogUtil::registerPermissionError();
        }

        // check for confirmation.
        if (empty($confirmation)) {
            // no confirmation yet - display a suitable form to obtain confirmation
            // of this action from the user

            $this->view->setCaching(false);

            // quote id
            $this->view->assign('qid', $qid);

            // return the output that has been generated by this function
            return $this->view->fetch('quotes_admin_delete.htm');
        }

        // if we get here it means that the user has confirmed the action

        // confirm authorisation code.
        if (!SecurityUtil::confirmAuthKey()) {
            return LogUtil::registerAuthidError(ModUtil::url('Quotes', 'admin', 'view'));
        }

        // delete the quote
        if (ModUtil::apiFunc('Quotes', 'admin', 'delete', array('qid' => $qid))) {
            LogUtil::registerStatus($this->__('Done! Quote deleted.'));
        }

        // This function generated no output, and so now it is complete we redirect
        // the user to an appropriate page for them to carry on their work
        return System::redirect(ModUtil::url('Quotes', 'admin', 'view'));
    }

    /**
     * Search quote database by keyword - unfinished obviously.
     * @author The Zikula Development Team
     * @return string HTML string
     */
    public function modifyconfig()
    {
        // security check
        if (!SecurityUtil::checkPermission('Quotes::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }

        $this->view->setCaching(false);
        // number of items to display per page + catmapcount
        $this->view->assign(ModUtil::getVar('Quotes'));

        // return the output that has been generated by this function
        return $this->view->fetch('quotes_admin_modifyconfig.htm');
    }
}